Update from source (#4)
* Update .tool-versions

* Gas price oracle: ignore gas price rounding for values less than 0.01

* GasPriceOracle.get_average_gas_price tests

* Switch to basic (non-pro) API endpoint for Coingecko requests, if api key is not provided

* Clear GA cache

* Remove Staking dapp logic from Blockscout core

* Remove staking-related tables

* Remove bridged tokens functionality from Blockscout core

* Change order of tables deletion in removal of Staking dapp functionality: staking_pools_delegators first, then staking_pools

* Drop staking_polls & stakin_pools_delegators tables with CASCADE flag

* Add clause for EthereumJSONRPC.Transaction.elixir_to_params/1 when gas_price is missing in the response

* Update debug_traceTransaction/tracer.js

TypeError: Assignment to constant variable. at putGas

* Update CHANGELOG

* Footer links management

* Change default footer chat link

Co-authored-by: Viktor Baranov <baranov.viktor.27@gmail.com>
Co-authored-by: Salisbury <salisbury.espinosa@gmail.com>